# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ElevationTilesToGeoTiff
                                 A QGIS plugin
 画面内の標高タイルを取得し、GeoTiffに変換します
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-08-27
        copyright            : (C) 2019 by nishio
        email                : nishio@mierune.co.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ElevationTilesToGeoTiff class from file ElevationTilesToGeoTiff.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .elevation_tiles_to_geotiff import ElevationTilesToGeoTiff
    return ElevationTilesToGeoTiff(iface)
